# Generated by Django 5.0.3 on 2024-03-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "first",
                    models.CharField(
                        help_text="The user's professional first name.",
                        max_length=255,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "middle",
                    models.CharField(
                        blank=True,
                        help_text="The user's professional middle name.",
                        max_length=255,
                        verbose_name="Middle Name",
                    ),
                ),
                (
                    "last",
                    models.CharField(
                        help_text="The user's professional last name.",
                        max_length=255,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_name",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
