# Generated by Django 5.0.3 on 2024-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalname",
            options={
                "verbose_name": "Professional Name",
                "verbose_name_plural": "Professional Names",
            },
        ),
        migrations.AddField(
            model_name="professionalname",
            name="suffix",
            field=models.CharField(
                blank=True,
                help_text="The user's professional suffix.",
                max_length=255,
                verbose_name="Suffix",
            ),
        ),
    ]
